# Generated by Django 5.2.15 on 2026-06-18 23:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرقم التعريفي')),
                ('role', models.CharField(choices=[('citizen', 'مواطن'), ('tier1', 'موظف فرز'), ('tier2', 'مختص'), ('admin', 'مدير عام')], default='citizen', max_length=20, verbose_name='الدور')),
                ('points', models.IntegerField(default=0, verbose_name='النقاط')),
                ('is_kyc_verified', models.BooleanField(default=False, verbose_name='موثق KYC')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم السجل')),
                ('action_type', models.CharField(max_length=255, verbose_name='نوع الإجراء')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='معرف المدير')),
                ('target_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targeted_logs', to=settings.AUTH_USER_MODEL, verbose_name='المواطن المستهدف')),
            ],
        ),
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الطلب')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('front_id_image', models.ImageField(upload_to='kyc/front/', verbose_name='صورة الهوية أمامي')),
                ('back_id_image', models.ImageField(upload_to='kyc/back/', verbose_name='صورة الهوية خلفي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to=settings.AUTH_USER_MODEL, verbose_name='معرف المواطن')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL, verbose_name='المدير المراجع')),
            ],
        ),
    ]
