# Generated by Django 5.2.15 on 2026-09-11 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_categories',
            field=models.ManyToManyField(blank=True, to='complaints.category', verbose_name='التصنيفات المسؤولة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_governorates',
            field=models.ManyToManyField(blank=True, to='complaints.governorate', verbose_name='المحافظات المسؤولة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='معرف المدير'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targeted_logs', to=settings.AUTH_USER_MODEL, verbose_name='المواطن المستهدف'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to=settings.AUTH_USER_MODEL, verbose_name='معرف المواطن'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL, verbose_name='المدير المراجع'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
