# Generated by Django 5.2.15 on 2026-09-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الهدية')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='كود الهدية (Voucher)')),
                ('required_points', models.IntegerField(verbose_name='النقاط المطلوبة')),
                ('instructions', models.TextField(default='يرجى إدخال هذا الكود في تطبيق المزود الخاص بك.', verbose_name='تعليمات الاستخدام')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='تم الاستلام؟')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL, verbose_name='المواطن المستلم')),
            ],
        ),
    ]
