# Generated by Django 5.2.15 on 2026-06-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_remove_customuser_role_and_more'),
        ('complaints', '0003_alter_attachment_id_alter_complaint_citizen_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.category', verbose_name='التصنيف المسؤول'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.governorate', verbose_name='المحافظة المسؤولة'),
        ),
    ]
