# Generated by Django 5.2.15 on 2026-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_managed_category_and_more'),
        ('complaints', '0004_complaint_current_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='managed_category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='managed_governorate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_categories',
            field=models.ManyToManyField(blank=True, to='complaints.category', verbose_name='التصنيفات المسؤولة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_governorates',
            field=models.ManyToManyField(blank=True, to='complaints.governorate', verbose_name='المحافظات المسؤولة'),
        ),
    ]
