# Generated by Django 5.2.15 on 2026-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_managed_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='الاسم الكامل'),
        ),
    ]
