# Generated by Django 5.2.15 on 2026-09-11 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم التصنيف')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المحافظة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('title', models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان الشكوى')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('location', models.CharField(default='غير محدد', max_length=255, verbose_name='الموقع التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='complaints_audio/', verbose_name='تسجيل صوتي')),
                ('status', models.CharField(choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], default='newStatus', max_length=20, verbose_name='حالة الشكوى')),
                ('specialist_message', models.TextField(blank=True, null=True, verbose_name='رسالة تحديث المختص')),
                ('citizen_rating', models.CharField(blank=True, choices=[('satisfied', 'تم الحل - راضٍ'), ('unsatisfied', 'إصلاح سيء - غير راضٍ')], max_length=20, null=True, verbose_name='تقييم المواطن')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.category', verbose_name='معرف التصنيف')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='معرف المواطن')),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول الحالي')),
                ('merged_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_tickets', to='complaints.complaint', verbose_name='تذكرة الدمج الأساسية')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.governorate', verbose_name='معرف المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='رقم المرفق')),
                ('file_link', models.FileField(upload_to='complaints_media/', verbose_name='رابط الملف')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint', verbose_name='معرف الشكوى')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الحركة')),
                ('old_status', models.CharField(blank=True, choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], max_length=20, null=True, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='محالة إلى')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint', verbose_name='معرف الشكوى')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
    ]
