# Generated by Django 5.2.15 on 2026-06-18 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم التصنيف')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المحافظة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('sorting', 'قيد الفرز'), ('assigned', 'محالة للمختص'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='حالة الشكوى')),
                ('specialist_message', models.TextField(blank=True, null=True, verbose_name='رسالة تحديث المختص')),
                ('citizen_rating', models.CharField(blank=True, max_length=50, null=True, verbose_name='تقييم المواطن')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.category', verbose_name='معرف التصنيف')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='معرف المواطن')),
                ('merged_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_tickets', to='complaints.complaint', verbose_name='تذكرة الدمج الأساسية')),
                ('sorter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorted_complaints', to=settings.AUTH_USER_MODEL, verbose_name='معرف موظف الفرز')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_complaints', to=settings.AUTH_USER_MODEL, verbose_name='معرف المختص')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.governorate', verbose_name='معرف المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المرفق')),
                ('file_link', models.FileField(upload_to='complaints_media/', verbose_name='رابط الملف')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint', verbose_name='معرف الشكوى')),
            ],
        ),
    ]
