# Generated by Django 5.2.15 on 2026-06-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='sorter',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='specialist',
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الحركة')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'جديدة'), ('sorting', 'قيد الفرز'), ('assigned', 'محالة للمختص'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], max_length=20, null=True, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('new', 'جديدة'), ('sorting', 'قيد الفرز'), ('assigned', 'محالة للمختص'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='محالة إلى')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint', verbose_name='معرف الشكوى')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
    ]
