# Generated by Django 5.2.15 on 2026-09-12 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='أولوية عاجلة'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_complaints', to=settings.AUTH_USER_MODEL, verbose_name='المواطنون المتأثرون'),
        ),
    ]
