# Generated by Django 5.2.15 on 2026-06-19 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_sorter_remove_complaint_specialist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='رقم المرفق'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_rating',
            field=models.CharField(blank=True, choices=[('satisfied', 'تم الحل - راضٍ'), ('unsatisfied', 'إصلاح سيء - غير راضٍ')], max_length=20, null=True, verbose_name='تقييم المواطن'),
        ),
    ]
