# Generated by Django 5.2.15 on 2026-08-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_current_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(default='غير محدد', max_length=255, verbose_name='الموقع التفصيلي'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان الشكوى'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.governorate', verbose_name='معرف المحافظة'),
        ),
    ]
