# Generated by Django 5.2.15 on 2026-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_location_complaint_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], default='newStatus', max_length=20, verbose_name='حالة الشكوى'),
        ),
        migrations.AlterField(
            model_name='complainthistory',
            name='new_status',
            field=models.CharField(choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='complainthistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('newStatus', 'جديدة'), ('assigned', 'محالة للمختص'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة'), ('closed', 'مغلقة')], max_length=20, null=True, verbose_name='الحالة السابقة'),
        ),
    ]
