# Generated by Django 5.2.15 on 2026-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الإعلان')),
                ('message_ar', models.TextField(verbose_name='الرسالة بالعربي')),
                ('message_en', models.TextField(verbose_name='الرسالة بالإنجليزي')),
                ('is_visible', models.BooleanField(default=True, verbose_name='حالة الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('governorates', models.ManyToManyField(blank=True, related_name='announcements', to='complaints.governorate', verbose_name='المحافظات المستهدفة')),
            ],
        ),
    ]
