# Generated by Django 5.2.15 on 2026-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_current_assignee'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyannouncement',
            name='governorates',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='complaints.governorate', verbose_name='المحافظات المستهدفة'),
        ),
    ]
